In [32]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from pandas.core.common import flatten

In [4]:
df = pd.read_csv("../data/CleanData/Ensemble_inputs.csv")

In [158]:
dft = pd.read_csv("../data/TestData/Ensemble_inputs_test.csv")

In [159]:
dfp = pd.read_csv("../data/PredictionData/Ensemble_inputs_predict.csv")

In [160]:
dft.head()

Unemployment  Unemployment actual  RealGDP  RealGDP actual  Core CPI  \
0  Unemployment             8.108333  RealGDP         1.84187  Core CPI   
1  Unemployment             3.891667  RealGDP         2.25568  Core CPI   
2  Unemployment             6.158333  RealGDP         2.28887  Core CPI   
3  Unemployment             3.683333  RealGDP         3.77257  Core CPI   
4  Unemployment             8.108333  RealGDP         2.70637  Core CPI   

   Core CPI actual  Core PCE  Core PCE actual  XGBoost Unemployment  \
0         2.182359  Core PCE         1.807526              6.441676   
1         1.750223  Core PCE         1.925557              4.550749   
2         1.727100  Core PCE         1.529039              5.555898   
3         1.723147  Core PCE         1.382284              4.832536   
4         2.191476  Core PCE         1.664742              4.796389   

   XGBoost RealGDP  XGBoost Core CPI  XGBoost Core PCE  \
0         1.900410          2.035018          1.860834   
1         2.282169          1.843338          1.765594   
2         0.044246          1.798239          1.284611   
3         4.163749          1.851205          1.433132   
4         2.204120          2.175217          1.728797   

   RandomForest Unemployment  RandomForest RealGDP  RandomForest Core CPI  \
0                   6.987024              1.866981               2.129060   
1                   4.419464              2.234235               1.908327   
2                   5.617917              0.150907               1.723542   
3                   5.542827              3.938920               1.789840   
4                   4.699725              2.290540               2.219719   

   RandomForest Core PCE  
0               1.888836  
1               1.858181  
2               1.402793  
3               1.366142  
4               1.685786

In [161]:
dfp.head()

Unemployment Unemployment actual  RealGDP RealGDP actual  Core CPI  \
0  Unemployment             Unknown  RealGDP        Unknown  Core CPI   
1  Unemployment             Unknown  RealGDP        Unknown  Core CPI   
2  Unemployment             Unknown  RealGDP        Unknown  Core CPI   
3  Unemployment             Unknown  RealGDP        Unknown  Core CPI   
4  Unemployment             Unknown  RealGDP        Unknown  Core CPI   

  Core CPI actual  Core PCE Core PCE actual  XGBoost Unemployment  \
0         Unknown  Core PCE         Unknown              7.393668   
1         Unknown  Core PCE         Unknown              7.910341   
2         Unknown  Core PCE         Unknown              7.739791   
3         Unknown  Core PCE         Unknown              6.362326   
4         Unknown  Core PCE         Unknown              7.531527   

   XGBoost RealGDP  XGBoost Core CPI  XGBoost Core PCE  \
0        -0.705191          1.713325          1.378743   
1        -1.261568          1.739907          1.388766   
2        -0.793215          1.737717          1.378743   
3        -0.388852          1.740747          1.373877   
4        -0.857580          1.720671          1.378743   

   RandomForest Unemployment  RandomForest RealGDP  RandomForest Core CPI  \
0                   7.335446             -0.109095               1.766475   
1                   7.871280             -2.209049               1.800801   
2                   7.665833              0.196510               1.769844   
3                   7.729048             -0.044055               1.796687   
4                   6.600268             -0.286090               1.730217   

   RandomForest Core PCE  
0               1.376086  
1               1.403231  
2               1.395988  
3               1.357659  
4               1.415595

# Data Prep Work

In [162]:
uX = df[["XGBoost Unemployment", "RandomForest Unemployment"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
uY = df[["Unemployment actual"]]

uX = uX.dropna()
uY = uY.dropna()

In [163]:
gX = df[["XGBoost RealGDP", "RandomForest RealGDP"]]#, "Linear Regression RealGDP", "KNeigborsRegressor RealGDP"]]
gY = df[["RealGDP actual"]]

In [164]:
cX = df[["XGBoost Core CPI", "RandomForest Core CPI"]]#, "Linear Regression Core CPI", "KNeigborsRegressor Core CPI"]]
cY = df[["Core CPI actual"]]

cX = cX.dropna()
cY = cY.dropna()

In [165]:
pX = df[["XGBoost Core PCE", "RandomForest Core PCE"]]#, "Linear Regression Core PCE", "KNeigborsRegressor Core PCE"]]
pY = df[["Core PCE actual"]]

pX = pX.dropna()
pY = pY.dropna()

# Train the Ensemble Weights

In [166]:
reg = LinearRegression().fit(gX, gY)
print(reg.score(gX, gY))

pred = reg.predict(gX)
actual = gY

np.sqrt(mean_squared_error(pred, actual))

0.7255517468974357


0.9605828153882446

In [167]:
reg.coef_

array([[0.7513008 , 0.23820811]])

In [168]:
gX = dft[["XGBoost RealGDP", "RandomForest RealGDP"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
gY = dft[["RealGDP actual"]]

gX = gX.dropna()
gY = gY.dropna()

print(reg.score(gX, gY))

testpred = reg.predict(gX)
actual = gY

np.sqrt(mean_squared_error(testpred, actual))

0.7166459190386019


0.9463284892883185

In [169]:
gX = dfp[["XGBoost RealGDP", "RandomForest RealGDP"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]

gX = gX.dropna()

testpredg = reg.predict(gX)

In [170]:
reg = LinearRegression().fit(uX, uY)
print(reg.score(uX, uY))

pred = reg.predict(uX)
actual = uY

np.sqrt(mean_squared_error(pred, actual))

0.7925541511778704


0.8812050404877251

In [171]:
reg.coef_

array([[0.89907881, 0.1030051 ]])

In [172]:
uX = dft[["XGBoost Unemployment", "RandomForest Unemployment"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
uY = dft[["Unemployment actual"]]

uX = uX.dropna()
uY = uY.dropna()

print(reg.score(uX, uY))

testpred = reg.predict(uX)
actual = uY

np.sqrt(mean_squared_error(testpred, actual))

0.7724688587635861


0.9139474764257247

In [173]:
uX = dfp[["XGBoost Unemployment", "RandomForest Unemployment"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]

uX = uX.dropna()

testpredu = reg.predict(uX)

In [174]:
reg = LinearRegression().fit(cX, cY)
print(reg.score(cX, cY))

pred = reg.predict(cX)
actual = cY

np.sqrt(mean_squared_error(pred, actual))

0.47296388930613054


0.2943635989333608

In [175]:
reg.coef_

array([[0.93280043, 0.14751195]])

In [176]:
cX = dft[["XGBoost Core CPI", "RandomForest Core CPI"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
cY = dft[["Core CPI actual"]]

cX = cX.dropna()
cY = cY.dropna()

print(reg.score(cX, cY))

testpred = reg.predict(cX)
actual = cY

np.sqrt(mean_squared_error(testpred, actual))

0.45839613833950144


0.30252214686701157

In [177]:
cX = dfp[["XGBoost Core CPI", "RandomForest Core CPI"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]

cX = cX.dropna()

testpredc = reg.predict(cX)

In [178]:
reg = LinearRegression().fit(pX, pY)
print(reg.score(pX, pY))

pred = reg.predict(pX)
actual = pY

np.sqrt(mean_squared_error(pred, actual))

0.5146228020778377


0.21094134019330718

In [179]:
reg.coef_

array([[1.05239414, 0.01996658]])

In [180]:
pX = dft[["XGBoost Core PCE", "RandomForest Core PCE"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
pY = dft[["Core PCE actual"]]

pX = pX.dropna()
pY = pY.dropna()

print(reg.score(pX, pY))

testpred = reg.predict(pX)
actual = pY

np.sqrt(mean_squared_error(testpred, actual))

0.4645981357349809


0.22088178791279664

In [181]:
pX = dfp[["XGBoost Core PCE", "RandomForest Core PCE"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]

pX = pX.dropna()

testpredp = reg.predict(pX)

# Do the Aggregate Predictions

In [183]:
# Get predictions set
dftt = pd.read_csv("../data/PredictionData/predict_set.csv")
dftt = dftt.drop("actual", axis=1)
#dftt.groupby("FORECASTER ID")
#len(dftt[dftt["INDICATOR"] == "RealGDP"].drop("actual", axis=1).dropna())
#dftt["INDICATOR"].unique()
dgdp = dftt[dftt["INDICATOR"] == "RealGDP"]
dgdp = dgdp.dropna()

dune = dftt[dftt["INDICATOR"] == "Unemployment"]
dune = dune.dropna()

dpce = dftt[dftt["INDICATOR"] == "Core PCE"]
dpce = dpce.dropna()

dcpi = dftt[dftt["INDICATOR"] == "Core CPI"]
dcpi = dcpi.dropna()

In [184]:
# Create Prediction Columns
dgdp["Preds"] = list(flatten(testpredg))
dune["Preds"] = list(flatten(testpredu))
dpce["Preds"] = list(flatten(testpredp))
dcpi["Preds"] = list(flatten(testpredc))

# Merge into prediction dataframe
dat = pd.concat([dgdp, dune, dpce, dcpi])
dat.head()

YEAR FORECAST MADE  YEAR BEING FORECAST  FORECASTER_CONF INDICATOR  \
1                 2019                 2022         0.288582   RealGDP   
6                 2019                 2022         0.335406   RealGDP   
7                 2019                 2022         0.306127   RealGDP   
9                 2019                 2022         0.256955   RealGDP   
10                2019                 2022         0.256112   RealGDP   

    pred_average  pred_var  banana      beef     bread   chicken      eggs  \
1           1.80    1.0100   0.576  3.761333  1.272333  1.475667  1.551667   
6           1.19    0.9139   0.576  3.761333  1.272333  1.475667  1.551667   
7           1.84    0.9044   0.576  3.761333  1.272333  1.475667  1.551667   
9           2.24    1.6524   0.576  3.761333  1.272333  1.475667  1.551667   
10          2.32    1.7476   0.576  3.761333  1.272333  1.475667  1.551667   

    electricity     flour  iceCream  unleadedGasoline     Preds  
1      0.135333  0.442333  4.894667             2.402 -0.546182  
6      0.135333  0.442333  4.894667             2.402 -1.464415  
7      0.135333  0.442333  4.894667             2.402 -0.539517  
9      0.135333  0.442333  4.894667             2.402 -0.293024  
10     0.135333  0.442333  4.894667             2.402 -0.702834

In [185]:
frame = pd.DataFrame({ "RealGDP Prediction": dat[dat["INDICATOR"]=="RealGDP"]["Preds"], "Year": dat[dat["INDICATOR"]=="RealGDP"]["YEAR BEING FORECAST"]})
groupedgdp = frame.groupby("Year").mean()
groupedgdp

RealGDP Prediction
Year                    
2022           -0.579815
2023           -0.654251
2024           -0.761541

In [186]:
frame = pd.DataFrame({ "Unemployment Prediction": dat[dat["INDICATOR"]=="Unemployment"]["Preds"], "Year": dat[dat["INDICATOR"]=="Unemployment"]["YEAR BEING FORECAST"]})
groupedune = frame.groupby("Year").mean()
groupedune

Unemployment Prediction
Year                         
2022                 7.129896
2023                 6.973807
2024                 7.014714

In [187]:
frame = pd.DataFrame({ "Core PCE Prediction": dat[dat["INDICATOR"]=="Core PCE"]["Preds"], "Year": dat[dat["INDICATOR"]=="Core PCE"]["YEAR BEING FORECAST"]})
groupedpce = frame.groupby("Year").mean()
groupedpce

Core PCE Prediction
Year                     
2022             1.452295

In [188]:
frame = pd.DataFrame({ "Core CPI Prediction": dat[dat["INDICATOR"]=="Core CPI"]["Preds"], "Year": dat[dat["INDICATOR"]=="Core CPI"]["YEAR BEING FORECAST"]})
groupedcpi = frame.groupby("Year").mean()
groupedcpi

Core CPI Prediction
Year                     
2022             1.782852

# Use Gridsearch Results

In [72]:
uX = dfs[["XGBoost Unemployment", "Random Forest Unemployment"]]
uY = dfs[["Unemployment actual"]]

uX = uX.dropna()
uY = uY.dropna()

In [73]:
gX = dfs[["XGBoost RealGDP", "Random Forest RealGDP"]]
gY = dfs[["RealGDP actual"]]

In [74]:
cX = dfs[["XGBoost Core CPI", "Random Forest Core CPI"]]
cY = dfs[["Core CPI actual"]]

cX = cX.dropna()
cY = cY.dropna()

In [75]:
pX = dfs[["XGBoost Core PCE", "Random Forest Core PCE"]]
pY = dfs[["Core PCE actual"]]

pX = pX.dropna()
pY = pY.dropna()

In [76]:
reg = LinearRegression().fit(gX, gY)
print(reg.score(gX, gY))

pred = reg.predict(gX)
actual = gY

np.sqrt(mean_squared_error(pred, actual))

0.9546869021295435


0.4100763638910511

In [77]:
reg.coef_

array([[0.42815693, 0.57616913]])

In [78]:
reg = LinearRegression().fit(uX, uY)
print(reg.score(uX, uY))

pred = reg.predict(uX)
actual = uY

np.sqrt(mean_squared_error(pred, actual))

0.9442919819963325


0.6702318731501157

In [79]:
reg.coef_

array([[0.74354694, 0.26637404]])

In [80]:
reg = LinearRegression().fit(cX, cY)
print(reg.score(cX, cY))

pred = reg.predict(cX)
actual = cY

np.sqrt(mean_squared_error(pred, actual))

0.922610484523368


0.337232509244397

In [81]:
reg.coef_

array([[-0.45484695,  1.50678078]])

In [82]:
reg = LinearRegression().fit(pX, pY)
print(reg.score(pX, pY))

pred = reg.predict(pX)
actual = pY

np.sqrt(mean_squared_error(pred, actual))

0.9039947016794517


0.37225918993422225

In [83]:
reg.coef_

array([[0.41344445, 0.59470852]])