In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from pandas.core.common import flatten

In [114]:
ts = pd.read_csv("/Users/Isaac/Documents/GitHub/W210-Capstone/models/Time Series/PredictionResults/GDPwSPFPreds.csv")
ts2 = pd.read_csv("/Users/Isaac/Documents/GitHub/W210-Capstone/models/Time Series/PredictionResults/GDPEvalandPreds.csv")

In [115]:
#df = pd.read_csv("../data/CleanData/Ensemble_inputs.csv")
df2 = pd.read_csv("/Users/Isaac/Downloads/model_preds.csv")
df = pd.read_csv("/Users/Isaac/Downloads/train_preds.csv")

In [116]:
#dft = pd.read_csv("../data/TestData/Ensemble_inputs_test.csv")
dft = pd.read_csv("/Users/Isaac/Downloads/test_preds.csv")

In [117]:
#dfp = pd.read_csv("../data/PredictionData/Ensemble_inputs_predict.csv")
dfp = pd.read_csv("/Users/Isaac/Downloads/future_preds.csv")

In [118]:
dfp = dfp[dfp["Year"] < 2023]
dfp

Unnamed: 0     SPF  Model Pred  Year
0          23259  1.9500    2.553776  2020
1          23264  0.9000    1.327014  2020
2          23265  2.2300    2.285147  2020
3          23267  1.7300    2.170181  2020
4          23269  3.0700    2.629726  2020
5          23270  2.0400    2.430910  2020
6          23271  1.5800    2.515279  2020
7          23272  2.0500    2.216792  2020
8          23273  1.0000    2.485052  2020
9          23274  1.5500    2.321415  2020
10         23275  2.3000    2.619771  2020
11         23276  2.5634    1.876200  2020
12         23277  1.5000    2.279505  2020
13         23279  2.4500    2.255527  2020
14         23282  3.0500    2.299813  2020
15         23285  2.2000    1.884375  2020
16         23287  2.5500    1.585137  2020
17         23288  1.9000    2.467389  2020
18         23289  2.7880    2.498891  2020
19         23290  1.4500    2.267083  2020
20         23292  1.6300    2.146934  2020
21         23293  1.7800    2.300159  2020
22         23713  1.9500    2.553776  2020
23         23716  2.3500    1.015072  2020
24         23718  0.9000    1.327014  2020
25         23719  2.1800    2.634616  2020
26         23721  2.1300    3.213088  2020
27         23722  2.9900    2.323836  2020
28         23723  2.0400    2.430910  2020
29         23725  2.0000    2.313625  2020
...          ...     ...         ...   ...
1110       30831  1.8000    3.248181  2022
1111       30832  2.5400    2.211737  2022
1112       30835  3.1500    3.101645  2022
1113       30837  2.9000    1.976489  2022
1114       30839  1.9400    3.434037  2022
1115       30840  2.0200    2.350413  2022
1116       30841  2.9500    2.610761  2022
1117       30842  2.5000    2.446278  2022
1118       30843  2.0000    2.310519  2022
1119       30844  3.2000    1.720519  2022
1120       30845  3.2500    2.254450  2022
1121       30846  3.4500    2.194533  2022
1122       30847  2.3500    2.295411  2022
1123       30848  3.3550    2.798587  2022
1124       30849  3.3500    2.173945  2022
1125       30850  2.8000    2.149935  2022
1126       30852  2.3500    2.572605  2022
1127       30853  3.5000    2.979929  2022
1128       30854  2.1200    2.242861  2022
1129       30855  2.7900    2.501579  2022
1130       30856  4.1500    3.366393  2022
1131       30857  2.0000    2.223437  2022
1132       30858  3.5500    2.876837  2022
1133       30859  3.2500    2.900180  2022
1134       30860  3.1410    2.579407  2022
1135       30861  1.8342    1.496995  2022
1136       30862  3.1500    2.978015  2022
1137       30863  2.5300    0.941197  2022
1138       30864  3.2500    4.482565  2022
1139       30865  2.5000    2.951360  2022

[1017 rows x 4 columns]

In [119]:
df2

Year   Actual       SPF  Model Val  Model Test
0   1992  3.52244  1.792117   2.283792    2.244451
1   1993  2.75179  2.829303   2.810716    2.806247
2   1994  4.02879  3.197719   3.086463    3.042563
3   1995  2.68421  2.827097   3.071939    3.069233
4   1996  3.77257  2.248873   3.021837    3.086144
5   1997  4.44717  2.704064   3.337892    3.445742
6   1998  4.48139  2.624405   3.268756    3.347521
7   1999  4.79450  3.012362   3.402202    3.426237
8   2000  4.07716  3.491066   3.377662    3.459130
9   2001  0.95434  2.383571   2.222692    2.361134
10  2002  1.69594  2.504100   2.269384    2.293628
11  2003  2.79621  2.704030   2.549534    2.567482
12  2004  3.85255  3.771259   3.069636    3.128276
13  2005  3.48322  3.552813   3.141300    3.131920
14  2006  2.78281  3.218136   2.678675    2.704400
15  2007  2.01051  2.488125   1.996002    2.023748
16  2008  0.12219  1.967766   1.338557    1.384109
17  2009 -2.59989 -0.384981  -1.137204   -1.176631
18  2010  2.70886  2.453549   1.919455    1.913586
19  2011  1.54990  2.534129   2.046163    2.069189
20  2012  2.28069  2.619186   2.096252    2.096707
21  2013  1.84187  2.338590   1.856493    1.864466
22  2014  2.28778  2.575329   2.120778    2.143086
23  2015  2.70637  2.666078   2.195138    2.204261
24  2016  1.66747  2.348168   2.037088    2.032455
25  2017  2.25568  2.306249   1.942373    1.979526
26  2018  2.91886  2.354740   2.147478    2.149903
27  2019  2.28887  2.198905   1.856245    1.883861
28  2020 -3.40459  1.213415  -0.177808   -0.312203

In [120]:
df

Unnamed: 0   Actual       SPF  Model Val  Year
0           6272 -2.59989  2.577223  -0.956356  2009
1          16879  2.28778  2.100000   2.404486  2014
2          13310  2.28069  2.450000   2.274789  2012
3          15714  1.66747  2.900000   1.977489  2016
4          15088  2.70637  2.800000   2.758521  2015
5           4755  0.12219  3.300000   1.119432  2008
6           2114  4.07716  2.200000   2.770534  2000
7            514  4.02879  2.800000   3.558559  1994
8           3891  3.48322  3.750000   3.641937  2005
9           1780  4.48139  3.200000   3.778984  1998
10          3705  3.48322  4.750000   3.497152  2005
11         15891  1.84187  1.600000   1.866968  2013
12          2824  1.69594  2.400000   2.712109  2002
13          2235  4.79450  3.550000   4.114300  1999
14         17408  2.28778  2.250000   2.389411  2014
15         15689  1.66747  2.550000   1.697057  2016
16           284  2.75179  2.250000   2.699775  1993
17         25412  2.28887  2.200000   2.345863  2019
18          1788  4.48139  2.300000   4.160658  1998
19         17911  2.28778  2.100000   2.468779  2014
20          1859  4.79450  1.900000   3.967312  1999
21          1378  3.77257  3.000000   3.550458  1996
22         15880  1.84187  1.990900   2.033729  2013
23         16202  1.66747  2.150000   1.947979  2016
24         16025  2.28778  2.350000   2.601069  2014
25         11759  1.54990  1.770000   2.042489  2011
26         15638  2.70637  2.718400   2.563227  2015
27         25405  2.28887  3.200000   2.288870  2019
28          1878  4.79450  2.530000   4.568473  1999
29          1997  4.79450  2.200000   4.474150  1999
...          ...      ...       ...        ...   ...
5844       10504  2.28069  2.825600   2.217813  2012
5845       12752  2.28069  2.550000   2.042915  2012
5846        2685  1.69594  1.610000   1.723354  2002
5847        7000 -2.59989 -1.150000  -2.599890  2009
5848        8117  2.28069  2.900000   2.438655  2012
5849        2410  0.95434  3.500000   1.901454  2001
5850         495  4.02879  2.500000   3.580752  1994
5851        5375  0.12219  1.860000   0.224362  2008
5852       11431  2.28069  3.050000   2.121177  2012
5853         614  2.68421  4.000000   3.395572  1995
5854        4338  2.78281  3.310000   3.129137  2006
5855        3920  3.48322  4.000000   3.604363  2005
5856       17062  2.70637  2.400000   2.598794  2015
5857        6559 -2.59989  1.600000  -1.195784  2009
5858        4305  2.78281  3.370000   2.736868  2006
5859       10478  2.28069  3.150000   2.159335  2012
5860        3543  3.85255  4.620000   3.869643  2004
5861         382  2.75179  3.100000   2.972731  1993
5862        3867  2.78281  2.750000   2.601746  2006
5863       11506  1.84187  2.060000   2.203439  2013
5864       11783  1.54990  2.500000   2.037510  2011
5865        2777  1.69594  2.400000   1.764488  2002
5866       15551  2.28778  3.000000   2.508812  2014
5867       17909  2.28778  2.050000   2.216792  2014
5868       24515  2.91886  2.300000   2.940757  2018
5869       10236  2.70886  2.500000   2.679178  2010
5870        1883  4.48139  3.000000   3.807910  1998
5871       20196  2.25568  2.360000   2.465446  2017
5872       25868  2.28887  1.690000   2.286750  2019
5873       23112  2.91886  2.450000   2.790814  2018

[5874 rows x 5 columns]

In [150]:
ts["year"] = ts["year"].astype(int)
#ts = ts.drop(columns = ["Unnamed: 0", "actual", "pred_average"])
ts
# 2021 : 
# 2022 : 
ts3 = ts
ts3.iloc[16,0] = 2.284382
ts3.iloc[16,1] = 2021
ts3 = ts3.append({"ts": 2.152472, "year": 2022}, ignore_index=True)
ts3

ts    year
0   4.365155  2005.0
1   3.824596  2006.0
2   1.741411  2007.0
3   0.017238  2008.0
4  -4.405738  2009.0
5   2.331425  2010.0
6   1.780707  2011.0
7   2.244782  2012.0
8   1.741338  2013.0
9   1.525327  2014.0
10  2.338382  2015.0
11  2.086048  2016.0
12  1.895883  2017.0
13  2.696346  2018.0
14  2.350946  2019.0
15 -0.654795  2020.0
16  2.284382  2021.0
17  2.152472  2022.0

In [151]:
dat = df.merge(ts, how="left", left_on='Year', right_on='year')
dat2 = dft.merge(ts, how="left", left_on='Year', right_on='year')
dat3 = dfp.merge(ts3, how="left", left_on='Year', right_on='year')

In [152]:
dat3 = dat3.drop(columns=["Unnamed: 0"])

dat3

SPF  Model Pred  Year        ts    year
0     1.9500    2.553776  2020 -0.654795  2020.0
1     0.9000    1.327014  2020 -0.654795  2020.0
2     2.2300    2.285147  2020 -0.654795  2020.0
3     1.7300    2.170181  2020 -0.654795  2020.0
4     3.0700    2.629726  2020 -0.654795  2020.0
5     2.0400    2.430910  2020 -0.654795  2020.0
6     1.5800    2.515279  2020 -0.654795  2020.0
7     2.0500    2.216792  2020 -0.654795  2020.0
8     1.0000    2.485052  2020 -0.654795  2020.0
9     1.5500    2.321415  2020 -0.654795  2020.0
10    2.3000    2.619771  2020 -0.654795  2020.0
11    2.5634    1.876200  2020 -0.654795  2020.0
12    1.5000    2.279505  2020 -0.654795  2020.0
13    2.4500    2.255527  2020 -0.654795  2020.0
14    3.0500    2.299813  2020 -0.654795  2020.0
15    2.2000    1.884375  2020 -0.654795  2020.0
16    2.5500    1.585137  2020 -0.654795  2020.0
17    1.9000    2.467389  2020 -0.654795  2020.0
18    2.7880    2.498891  2020 -0.654795  2020.0
19    1.4500    2.267083  2020 -0.654795  2020.0
20    1.6300    2.146934  2020 -0.654795  2020.0
21    1.7800    2.300159  2020 -0.654795  2020.0
22    1.9500    2.553776  2020 -0.654795  2020.0
23    2.3500    1.015072  2020 -0.654795  2020.0
24    0.9000    1.327014  2020 -0.654795  2020.0
25    2.1800    2.634616  2020 -0.654795  2020.0
26    2.1300    3.213088  2020 -0.654795  2020.0
27    2.9900    2.323836  2020 -0.654795  2020.0
28    2.0400    2.430910  2020 -0.654795  2020.0
29    2.0000    2.313625  2020 -0.654795  2020.0
...      ...         ...   ...       ...     ...
987   1.8000    3.248181  2022  2.152472  2022.0
988   2.5400    2.211737  2022  2.152472  2022.0
989   3.1500    3.101645  2022  2.152472  2022.0
990   2.9000    1.976489  2022  2.152472  2022.0
991   1.9400    3.434037  2022  2.152472  2022.0
992   2.0200    2.350413  2022  2.152472  2022.0
993   2.9500    2.610761  2022  2.152472  2022.0
994   2.5000    2.446278  2022  2.152472  2022.0
995   2.0000    2.310519  2022  2.152472  2022.0
996   3.2000    1.720519  2022  2.152472  2022.0
997   3.2500    2.254450  2022  2.152472  2022.0
998   3.4500    2.194533  2022  2.152472  2022.0
999   2.3500    2.295411  2022  2.152472  2022.0
1000  3.3550    2.798587  2022  2.152472  2022.0
1001  3.3500    2.173945  2022  2.152472  2022.0
1002  2.8000    2.149935  2022  2.152472  2022.0
1003  2.3500    2.572605  2022  2.152472  2022.0
1004  3.5000    2.979929  2022  2.152472  2022.0
1005  2.1200    2.242861  2022  2.152472  2022.0
1006  2.7900    2.501579  2022  2.152472  2022.0
1007  4.1500    3.366393  2022  2.152472  2022.0
1008  2.0000    2.223437  2022  2.152472  2022.0
1009  3.5500    2.876837  2022  2.152472  2022.0
1010  3.2500    2.900180  2022  2.152472  2022.0
1011  3.1410    2.579407  2022  2.152472  2022.0
1012  1.8342    1.496995  2022  2.152472  2022.0
1013  3.1500    2.978015  2022  2.152472  2022.0
1014  2.5300    0.941197  2022  2.152472  2022.0
1015  3.2500    4.482565  2022  2.152472  2022.0
1016  2.5000    2.951360  2022  2.152472  2022.0

[1017 rows x 5 columns]

In [153]:
#dat = dat.drop(columns = ["Unnamed: 0", "actual", "pred_average", "year"])
#dat = dat.iloc[13:, ]
dat = dat.drop(columns=["Unnamed: 0"])
dat

Actual       SPF  Model Val  Year        ts    year
0    -2.59989  2.577223  -0.956356  2009 -4.405738  2009.0
1     2.28778  2.100000   2.404486  2014  1.525327  2014.0
2     2.28069  2.450000   2.274789  2012  2.244782  2012.0
3     1.66747  2.900000   1.977489  2016  2.086048  2016.0
4     2.70637  2.800000   2.758521  2015  2.338382  2015.0
5     0.12219  3.300000   1.119432  2008  0.017238  2008.0
6     4.07716  2.200000   2.770534  2000       NaN     NaN
7     4.02879  2.800000   3.558559  1994       NaN     NaN
8     3.48322  3.750000   3.641937  2005  4.365155  2005.0
9     4.48139  3.200000   3.778984  1998       NaN     NaN
10    3.48322  4.750000   3.497152  2005  4.365155  2005.0
11    1.84187  1.600000   1.866968  2013  1.741338  2013.0
12    1.69594  2.400000   2.712109  2002       NaN     NaN
13    4.79450  3.550000   4.114300  1999       NaN     NaN
14    2.28778  2.250000   2.389411  2014  1.525327  2014.0
15    1.66747  2.550000   1.697057  2016  2.086048  2016.0
16    2.75179  2.250000   2.699775  1993       NaN     NaN
17    2.28887  2.200000   2.345863  2019  2.350946  2019.0
18    4.48139  2.300000   4.160658  1998       NaN     NaN
19    2.28778  2.100000   2.468779  2014  1.525327  2014.0
20    4.79450  1.900000   3.967312  1999       NaN     NaN
21    3.77257  3.000000   3.550458  1996       NaN     NaN
22    1.84187  1.990900   2.033729  2013  1.741338  2013.0
23    1.66747  2.150000   1.947979  2016  2.086048  2016.0
24    2.28778  2.350000   2.601069  2014  1.525327  2014.0
25    1.54990  1.770000   2.042489  2011  1.780707  2011.0
26    2.70637  2.718400   2.563227  2015  2.338382  2015.0
27    2.28887  3.200000   2.288870  2019  2.350946  2019.0
28    4.79450  2.530000   4.568473  1999       NaN     NaN
29    4.79450  2.200000   4.474150  1999       NaN     NaN
...       ...       ...        ...   ...       ...     ...
5844  2.28069  2.825600   2.217813  2012  2.244782  2012.0
5845  2.28069  2.550000   2.042915  2012  2.244782  2012.0
5846  1.69594  1.610000   1.723354  2002       NaN     NaN
5847 -2.59989 -1.150000  -2.599890  2009 -4.405738  2009.0
5848  2.28069  2.900000   2.438655  2012  2.244782  2012.0
5849  0.95434  3.500000   1.901454  2001       NaN     NaN
5850  4.02879  2.500000   3.580752  1994       NaN     NaN
5851  0.12219  1.860000   0.224362  2008  0.017238  2008.0
5852  2.28069  3.050000   2.121177  2012  2.244782  2012.0
5853  2.68421  4.000000   3.395572  1995       NaN     NaN
5854  2.78281  3.310000   3.129137  2006  3.824596  2006.0
5855  3.48322  4.000000   3.604363  2005  4.365155  2005.0
5856  2.70637  2.400000   2.598794  2015  2.338382  2015.0
5857 -2.59989  1.600000  -1.195784  2009 -4.405738  2009.0
5858  2.78281  3.370000   2.736868  2006  3.824596  2006.0
5859  2.28069  3.150000   2.159335  2012  2.244782  2012.0
5860  3.85255  4.620000   3.869643  2004       NaN     NaN
5861  2.75179  3.100000   2.972731  1993       NaN     NaN
5862  2.78281  2.750000   2.601746  2006  3.824596  2006.0
5863  1.84187  2.060000   2.203439  2013  1.741338  2013.0
5864  1.54990  2.500000   2.037510  2011  1.780707  2011.0
5865  1.69594  2.400000   1.764488  2002       NaN     NaN
5866  2.28778  3.000000   2.508812  2014  1.525327  2014.0
5867  2.28778  2.050000   2.216792  2014  1.525327  2014.0
5868  2.91886  2.300000   2.940757  2018  2.696346  2018.0
5869  2.70886  2.500000   2.679178  2010  2.331425  2010.0
5870  4.48139  3.000000   3.807910  1998       NaN     NaN
5871  2.25568  2.360000   2.465446  2017  1.895883  2017.0
5872  2.28887  1.690000   2.286750  2019  2.350946  2019.0
5873  2.91886  2.450000   2.790814  2018  2.696346  2018.0

[5874 rows x 6 columns]

In [154]:
dat2 = dat2.drop(columns=["Unnamed: 0"])
dat2

Actual       SPF  Model Test  Year        ts    year
0     2.28069  2.280000    1.901683  2012  2.244782  2012.0
1     2.28887  2.400000    2.342085  2019  2.350946  2019.0
2     2.70637  2.500000    2.733985  2015  2.338382  2015.0
3     2.91886  2.500000    2.679203  2018  2.696346  2018.0
4     2.79621  2.800000    2.128564  2003       NaN     NaN
5     2.01051  2.450000    2.375712  2007  1.741411  2007.0
6     1.54990  2.100000    2.027075  2011  1.780707  2011.0
7     0.95434  2.730000    2.844062  2001       NaN     NaN
8    -3.40459  1.700000   -0.457095  2020 -0.654795  2020.0
9     2.70886  2.000000    1.839226  2010  2.331425  2010.0
10   -3.40459 -1.850000   -2.921770  2020 -0.654795  2020.0
11    3.52244  1.800000    2.194114  1992       NaN     NaN
12    0.12219  1.400000    0.695691  2008  0.017238  2008.0
13    2.01051  3.450000    2.814467  2007  1.741411  2007.0
14    0.12219  1.500000    0.399985  2008  0.017238  2008.0
15    2.28778  2.400000    2.246970  2014  1.525327  2014.0
16    2.78281  3.000000    2.323512  2006  3.824596  2006.0
17    4.07716  2.860000    4.076627  2000       NaN     NaN
18    2.25568  2.450000   -0.913009  2017  1.895883  2017.0
19    2.01051  2.950000    1.458523  2007  1.741411  2007.0
20    2.28887  1.150000    2.688767  2019  2.350946  2019.0
21    2.25568  2.100000    0.755654  2017  1.895883  2017.0
22    1.54990  3.260000    2.279777  2011  1.780707  2011.0
23    2.01051  1.700000    1.980036  2007  1.741411  2007.0
24    4.44717  2.300000    3.919508  1997       NaN     NaN
25    3.85255  4.710000    3.747037  2004       NaN     NaN
26    2.28778  2.100000    2.157067  2014  1.525327  2014.0
27    4.02879  3.650000    3.809414  1994       NaN     NaN
28    2.28778  1.800000   -0.938744  2014  1.525327  2014.0
29    2.28778  2.780000    1.376368  2014  1.525327  2014.0
...       ...       ...         ...   ...       ...     ...
2015  4.48139  2.350000    3.856426  1998       NaN     NaN
2016  4.02879  2.400000    2.762748  1994       NaN     NaN
2017  1.54990  2.950000    2.160474  2011  1.780707  2011.0
2018  4.79450  1.800000    4.335711  1999       NaN     NaN
2019  2.28887  3.054000    2.284337  2019  2.350946  2019.0
2020 -2.59989 -2.400000   -2.509809  2009 -4.405738  2009.0
2021 -3.40459  2.000000    1.224104  2020 -0.654795  2020.0
2022  2.68421  2.900000    2.933877  1995       NaN     NaN
2023  2.28069  2.050000    3.162750  2012  2.244782  2012.0
2024  2.70886  2.700000    2.542022  2010  2.331425  2010.0
2025  0.12219  2.800000    1.314306  2008  0.017238  2008.0
2026  2.91886  3.500000    2.864444  2018  2.696346  2018.0
2027  2.28887  2.550000   -1.624403  2019  2.350946  2019.0
2028  1.66747  2.590000    1.907733  2016  2.086048  2016.0
2029  1.84187  1.600000    2.889545  2013  1.741338  2013.0
2030  3.77257  2.480000    2.740984  1996       NaN     NaN
2031  1.54990  1.600000    1.563796  2011  1.780707  2011.0
2032  0.95434  3.050000    4.445265  2001       NaN     NaN
2033  2.28778  2.500000    2.888090  2014  1.525327  2014.0
2034  2.78281  2.250000    2.645904  2006  3.824596  2006.0
2035  2.28778  2.050000    2.919951  2014  1.525327  2014.0
2036  3.77257  1.750000    2.233840  1996       NaN     NaN
2037  3.52244  1.600000    0.819898  1992       NaN     NaN
2038  2.70637  3.400000    3.292116  2015  2.338382  2015.0
2039  1.66747  1.393000    2.666454  2016  2.086048  2016.0
2040  4.44717  3.200000    3.410762  1997       NaN     NaN
2041  4.02879  3.980996    4.237001  1994       NaN     NaN
2042  4.44717  2.420000    2.186360  1997       NaN     NaN
2043  2.25568  2.300000    2.103345  2017  1.895883  2017.0
2044  2.91886  1.950000    2.168085  2018  2.696346  2018.0

[2045 rows x 6 columns]

In [155]:
dat = dat.dropna()
gX = dat[["Model Val", "ts"]]
gX#, "Linear Regression RealGDP", "KNeigborsRegressor RealGDP"]]
gY = dat[["Actual"]]

In [156]:
reg = LinearRegression().fit(gX, gY)
print(reg.score(gX, gY))

pred = reg.predict(gX)
actual = gY

np.sqrt(mean_squared_error(pred, actual))

0.940967489890382


0.30162758593787753

In [157]:
reg.coef_

array([[0.45484955, 0.4485225 ]])

In [158]:
dat2 = dat2.dropna()

gX = dat2[["Model Test", "ts"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
gY = dat2[["Actual"]]

gX = gX.dropna()
gY = gY.dropna()

print(reg.score(gX, gY))

testpred = reg.predict(gX)
actual = gY

print(np.sqrt(mean_squared_error(testpred, actual)))
print(np.sqrt(mean_squared_error(dat2["SPF"], actual)))

0.6981859907683472
0.9736612439197876
1.589616950604771


In [159]:
dat3 = dat3.dropna()

gX = dat3[["Model Pred", "ts"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
#gY = dat2[["Actual"]]

gX = gX.dropna()
#gY = gY.dropna()

#print(reg.score(gX, gY))

testpred = reg.predict(gX)
#actual = gY

#print(np.sqrt(mean_squared_error(testpred, actual)))
#print(np.sqrt(mean_squared_error(dat2["SPF"], actual)))
dat3["predictions"] = testpred

testdatamaybe2 = dat3.groupby("Year").agg({"predictions": np.mean, "SPF": np.mean})
tosave = testdatamaybe2.iloc[1:, ]
tosave.to_csv("/Users/Isaac/Downloads/EnsembleFuturePredictions.csv")

In [97]:
dat2["predictions"] = testpred
dat2

Actual    SPF  Model Test  Year        ts    year  predictions
0     2.28069  2.280    1.901683  2012  2.244782  2012.0     2.085390
1     2.28887  2.400    2.342085  2019  2.350946  2019.0     2.333323
2     2.70637  2.500    2.733985  2015  2.338382  2015.0     2.505943
3     2.91886  2.500    2.679203  2018  2.696346  2018.0     2.641581
5     2.01051  2.450    2.375712  2007  1.741411  2007.0     2.075228
6     1.54990  2.100    2.027075  2011  1.780707  2011.0     1.934276
8    -3.40459  1.700   -0.457095  2020 -0.654795  2020.0    -0.288025
9     2.70886  2.000    1.839226  2010  2.331425  2010.0     2.095842
10   -3.40459 -1.850   -2.921770  2020 -0.654795  2020.0    -1.409082
12    0.12219  1.400    0.695691  2008  0.017238  2008.0     0.537741
13    2.01051  3.450    2.814467  2007  1.741411  2007.0     2.274796
14    0.12219  1.500    0.399985  2008  0.017238  2008.0     0.403239
15    2.28778  2.400    2.246970  2014  1.525327  2014.0     1.919751
16    2.78281  3.000    2.323512  2006  3.824596  2006.0     2.985840
18    2.25568  2.450   -0.913009  2017  1.895883  2017.0     0.648639
19    2.01051  2.950    1.458523  2007  1.741411  2007.0     1.658046
20    2.28887  1.150    2.688767  2019  2.350946  2019.0     2.491011
21    2.25568  2.100    0.755654  2017  1.895883  2017.0     1.407630
22    1.54990  3.260    2.279777  2011  1.780707  2011.0     2.049218
23    2.01051  1.700    1.980036  2007  1.741411  2007.0     1.895255
26    2.28778  2.100    2.157067  2014  1.525327  2014.0     1.878859
28    2.28778  1.800   -0.938744  2014  1.525327  2014.0     0.470731
29    2.28778  2.780    1.376368  2014  1.525327  2014.0     1.523758
30    1.66747  1.200    1.787355  2016  2.086048  2016.0     1.962192
31    2.25568  2.410    2.457978  2017  1.895883  2017.0     2.181931
32    2.28887  2.900    2.447974  2019  2.350946  2019.0     2.381486
35    1.84187  1.800    1.512731  2013  1.741338  2013.0     1.682669
36   -3.40459  1.780   -2.810648  2020 -0.654795  2020.0    -1.358538
37    2.25568  2.840    2.270851  2017  1.895883  2017.0     2.096816
38    2.70886  4.650    3.537648  2010  2.331425  2010.0     2.868368
...       ...    ...         ...   ...       ...     ...          ...
1997  2.70886  2.700    1.629428  2010  2.331425  2010.0     2.000416
1999  1.84187  2.610    1.854091  2013  1.741338  2013.0     1.837937
2000  2.70886  3.350    3.229423  2010  2.331425  2010.0     2.728172
2004  0.12219  1.480    1.810006  2008  0.017238  2008.0     1.044586
2005  0.12219  1.950    0.757680  2008  0.017238  2008.0     0.565936
2009  2.91886  2.250    3.146301  2018  2.696346  2018.0     2.854040
2010  2.28778  2.010    2.285007  2014  1.525327  2014.0     1.937052
2011  2.28778  1.500   -0.792617  2014  1.525327  2014.0     0.537196
2012  1.54990  2.800    1.855958  2011  1.780707  2011.0     1.856444
2013  2.28887  2.300    2.574478  2019  2.350946  2019.0     2.439027
2014  2.70886  1.500    0.249063  2010  2.331425  2010.0     1.372557
2017  1.54990  2.950    2.160474  2011  1.780707  2011.0     1.994952
2019  2.28887  3.054    2.284337  2019  2.350946  2019.0     2.307056
2020 -2.59989 -2.400   -2.509809  2009 -4.405738  2009.0    -2.904083
2021 -3.40459  2.000    1.224104  2020 -0.654795  2020.0     0.476667
2023  2.28069  2.050    3.162750  2012  2.244782  2012.0     2.658985
2024  2.70886  2.700    2.542022  2010  2.331425  2010.0     2.415508
2025  0.12219  2.800    1.314306  2008  0.017238  2008.0     0.819118
2026  2.91886  3.500    2.864444  2018  2.696346  2018.0     2.725838
2027  2.28887  2.550   -1.624403  2019  2.350946  2019.0     0.529168
2028  1.66747  2.590    1.907733  2016  2.086048  2016.0     2.016945
2029  1.84187  1.600    2.889545  2013  1.741338  2013.0     2.308912
2031  1.54990  1.600    1.563796  2011  1.780707  2011.0     1.723554
2033  2.28778  2.500    2.888090  2014  1.525327  2014.0     2.211364
2034  2.78281  2.250    2.645904  2006  3.824596  2006.0     3.132480
2035  2.28778  2.

In [130]:
testdatamaybe = dat2.groupby("Year").agg({"predictions": np.mean, "SPF": np.mean, "Actual": np.mean})
testdatamaybe
testdatamaybe.to_csv("/Users/Isaac/Downloads/EnsemblePredictions.csv")

In [108]:
print(np.sqrt(mean_squared_error(testdatamaybe["predictions"], testdatamaybe["Actual"])))
print(np.sqrt(mean_squared_error(testdatamaybe["SPF"], testdatamaybe["Actual"])))

0.8780617952186635
1.4076136866686604


In [ ]:
gX = dfp[["XGBoost RealGDP", "RandomForest RealGDP"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]

gX = gX.dropna()

testpredg = reg.predict(gX)

In [22]:
df

Year   Actual       SPF  Model Val  Model Test
0   1992  3.52244  1.792117   2.283792    2.244451
1   1993  2.75179  2.829303   2.810716    2.806247
2   1994  4.02879  3.197719   3.086463    3.042563
3   1995  2.68421  2.827097   3.071939    3.069233
4   1996  3.77257  2.248873   3.021837    3.086144
5   1997  4.44717  2.704064   3.337892    3.445742
6   1998  4.48139  2.624405   3.268756    3.347521
7   1999  4.79450  3.012362   3.402202    3.426237
8   2000  4.07716  3.491066   3.377662    3.459130
9   2001  0.95434  2.383571   2.222692    2.361134
10  2002  1.69594  2.504100   2.269384    2.293628
11  2003  2.79621  2.704030   2.549534    2.567482
12  2004  3.85255  3.771259   3.069636    3.128276
13  2005  3.48322  3.552813   3.141300    3.131920
14  2006  2.78281  3.218136   2.678675    2.704400
15  2007  2.01051  2.488125   1.996002    2.023748
16  2008  0.12219  1.967766   1.338557    1.384109
17  2009 -2.59989 -0.384981  -1.137204   -1.176631
18  2010  2.70886  2.453549   1.919455    1.913586
19  2011  1.54990  2.534129   2.046163    2.069189
20  2012  2.28069  2.619186   2.096252    2.096707
21  2013  1.84187  2.338590   1.856493    1.864466
22  2014  2.28778  2.575329   2.120778    2.143086
23  2015  2.70637  2.666078   2.195138    2.204261
24  2016  1.66747  2.348168   2.037088    2.032455
25  2017  2.25568  2.306249   1.942373    1.979526
26  2018  2.91886  2.354740   2.147478    2.149903
27  2019  2.28887  2.198905   1.856245    1.883861
28  2020 -3.40459  1.213415  -0.177808   -0.312203

In [15]:
df.head()

Year   Actual       SPF  Model Val  Model Test
0  1992  3.52244  1.792117   2.283792    2.244451
1  1993  2.75179  2.829303   2.810716    2.806247
2  1994  4.02879  3.197719   3.086463    3.042563
3  1995  2.68421  2.827097   3.071939    3.069233
4  1996  3.77257  2.248873   3.021837    3.086144

In [161]:
dfp.head()

Unemployment Unemployment actual  RealGDP RealGDP actual  Core CPI  \
0  Unemployment             Unknown  RealGDP        Unknown  Core CPI   
1  Unemployment             Unknown  RealGDP        Unknown  Core CPI   
2  Unemployment             Unknown  RealGDP        Unknown  Core CPI   
3  Unemployment             Unknown  RealGDP        Unknown  Core CPI   
4  Unemployment             Unknown  RealGDP        Unknown  Core CPI   

  Core CPI actual  Core PCE Core PCE actual  XGBoost Unemployment  \
0         Unknown  Core PCE         Unknown              7.393668   
1         Unknown  Core PCE         Unknown              7.910341   
2         Unknown  Core PCE         Unknown              7.739791   
3         Unknown  Core PCE         Unknown              6.362326   
4         Unknown  Core PCE         Unknown              7.531527   

   XGBoost RealGDP  XGBoost Core CPI  XGBoost Core PCE  \
0        -0.705191          1.713325          1.378743   
1        -1.261568          1.739907          1.388766   
2        -0.793215          1.737717          1.378743   
3        -0.388852          1.740747          1.373877   
4        -0.857580          1.720671          1.378743   

   RandomForest Unemployment  RandomForest RealGDP  RandomForest Core CPI  \
0                   7.335446             -0.109095               1.766475   
1                   7.871280             -2.209049               1.800801   
2                   7.665833              0.196510               1.769844   
3                   7.729048             -0.044055               1.796687   
4                   6.600268             -0.286090               1.730217   

   RandomForest Core PCE  
0               1.376086  
1               1.403231  
2               1.395988  
3               1.357659  
4               1.415595

# Data Prep Work

In [162]:
uX = df[["XGBoost Unemployment", "RandomForest Unemployment"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
uY = df[["Unemployment actual"]]

uX = uX.dropna()
uY = uY.dropna()

In [163]:
gX = df[["XGBoost RealGDP", "RandomForest RealGDP"]]#, "Linear Regression RealGDP", "KNeigborsRegressor RealGDP"]]
gY = df[["RealGDP actual"]]

In [164]:
cX = df[["XGBoost Core CPI", "RandomForest Core CPI"]]#, "Linear Regression Core CPI", "KNeigborsRegressor Core CPI"]]
cY = df[["Core CPI actual"]]

cX = cX.dropna()
cY = cY.dropna()

In [165]:
pX = df[["XGBoost Core PCE", "RandomForest Core PCE"]]#, "Linear Regression Core PCE", "KNeigborsRegressor Core PCE"]]
pY = df[["Core PCE actual"]]

pX = pX.dropna()
pY = pY.dropna()

# Train the Ensemble Weights

In [166]:
reg = LinearRegression().fit(gX, gY)
print(reg.score(gX, gY))

pred = reg.predict(gX)
actual = gY

np.sqrt(mean_squared_error(pred, actual))

0.7255517468974357


0.9605828153882446

In [167]:
reg.coef_

array([[0.7513008 , 0.23820811]])

In [168]:
gX = dft[["XGBoost RealGDP", "RandomForest RealGDP"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
gY = dft[["RealGDP actual"]]

gX = gX.dropna()
gY = gY.dropna()

print(reg.score(gX, gY))

testpred = reg.predict(gX)
actual = gY

np.sqrt(mean_squared_error(testpred, actual))

0.7166459190386019


0.9463284892883185

In [169]:
gX = dfp[["XGBoost RealGDP", "RandomForest RealGDP"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]

gX = gX.dropna()

testpredg = reg.predict(gX)

In [170]:
reg = LinearRegression().fit(uX, uY)
print(reg.score(uX, uY))

pred = reg.predict(uX)
actual = uY

np.sqrt(mean_squared_error(pred, actual))

0.7925541511778704


0.8812050404877251

In [171]:
reg.coef_

array([[0.89907881, 0.1030051 ]])

In [172]:
uX = dft[["XGBoost Unemployment", "RandomForest Unemployment"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
uY = dft[["Unemployment actual"]]

uX = uX.dropna()
uY = uY.dropna()

print(reg.score(uX, uY))

testpred = reg.predict(uX)
actual = uY

np.sqrt(mean_squared_error(testpred, actual))

0.7724688587635861


0.9139474764257247

In [173]:
uX = dfp[["XGBoost Unemployment", "RandomForest Unemployment"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]

uX = uX.dropna()

testpredu = reg.predict(uX)

In [174]:
reg = LinearRegression().fit(cX, cY)
print(reg.score(cX, cY))

pred = reg.predict(cX)
actual = cY

np.sqrt(mean_squared_error(pred, actual))

0.47296388930613054


0.2943635989333608

In [175]:
reg.coef_

array([[0.93280043, 0.14751195]])

In [176]:
cX = dft[["XGBoost Core CPI", "RandomForest Core CPI"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
cY = dft[["Core CPI actual"]]

cX = cX.dropna()
cY = cY.dropna()

print(reg.score(cX, cY))

testpred = reg.predict(cX)
actual = cY

np.sqrt(mean_squared_error(testpred, actual))

0.45839613833950144


0.30252214686701157

In [177]:
cX = dfp[["XGBoost Core CPI", "RandomForest Core CPI"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]

cX = cX.dropna()

testpredc = reg.predict(cX)

In [178]:
reg = LinearRegression().fit(pX, pY)
print(reg.score(pX, pY))

pred = reg.predict(pX)
actual = pY

np.sqrt(mean_squared_error(pred, actual))

0.5146228020778377


0.21094134019330718

In [179]:
reg.coef_

array([[1.05239414, 0.01996658]])

In [180]:
pX = dft[["XGBoost Core PCE", "RandomForest Core PCE"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
pY = dft[["Core PCE actual"]]

pX = pX.dropna()
pY = pY.dropna()

print(reg.score(pX, pY))

testpred = reg.predict(pX)
actual = pY

np.sqrt(mean_squared_error(testpred, actual))

0.4645981357349809


0.22088178791279664

In [181]:
pX = dfp[["XGBoost Core PCE", "RandomForest Core PCE"]]#, "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]

pX = pX.dropna()

testpredp = reg.predict(pX)

# Do the Aggregate Predictions

In [183]:
# Get predictions set
dftt = pd.read_csv("../data/PredictionData/predict_set.csv")
dftt = dftt.drop("actual", axis=1)
#dftt.groupby("FORECASTER ID")
#len(dftt[dftt["INDICATOR"] == "RealGDP"].drop("actual", axis=1).dropna())
#dftt["INDICATOR"].unique()
dgdp = dftt[dftt["INDICATOR"] == "RealGDP"]
dgdp = dgdp.dropna()

dune = dftt[dftt["INDICATOR"] == "Unemployment"]
dune = dune.dropna()

dpce = dftt[dftt["INDICATOR"] == "Core PCE"]
dpce = dpce.dropna()

dcpi = dftt[dftt["INDICATOR"] == "Core CPI"]
dcpi = dcpi.dropna()

In [184]:
# Create Prediction Columns
dgdp["Preds"] = list(flatten(testpredg))
dune["Preds"] = list(flatten(testpredu))
dpce["Preds"] = list(flatten(testpredp))
dcpi["Preds"] = list(flatten(testpredc))

# Merge into prediction dataframe
dat = pd.concat([dgdp, dune, dpce, dcpi])
dat.head()

YEAR FORECAST MADE  YEAR BEING FORECAST  FORECASTER_CONF INDICATOR  \
1                 2019                 2022         0.288582   RealGDP   
6                 2019                 2022         0.335406   RealGDP   
7                 2019                 2022         0.306127   RealGDP   
9                 2019                 2022         0.256955   RealGDP   
10                2019                 2022         0.256112   RealGDP   

    pred_average  pred_var  banana      beef     bread   chicken      eggs  \
1           1.80    1.0100   0.576  3.761333  1.272333  1.475667  1.551667   
6           1.19    0.9139   0.576  3.761333  1.272333  1.475667  1.551667   
7           1.84    0.9044   0.576  3.761333  1.272333  1.475667  1.551667   
9           2.24    1.6524   0.576  3.761333  1.272333  1.475667  1.551667   
10          2.32    1.7476   0.576  3.761333  1.272333  1.475667  1.551667   

    electricity     flour  iceCream  unleadedGasoline     Preds  
1      0.135333  0.442333  4.894667             2.402 -0.546182  
6      0.135333  0.442333  4.894667             2.402 -1.464415  
7      0.135333  0.442333  4.894667             2.402 -0.539517  
9      0.135333  0.442333  4.894667             2.402 -0.293024  
10     0.135333  0.442333  4.894667             2.402 -0.702834

In [185]:
frame = pd.DataFrame({ "RealGDP Prediction": dat[dat["INDICATOR"]=="RealGDP"]["Preds"], "Year": dat[dat["INDICATOR"]=="RealGDP"]["YEAR BEING FORECAST"]})
groupedgdp = frame.groupby("Year").mean()
groupedgdp

RealGDP Prediction
Year                    
2022           -0.579815
2023           -0.654251
2024           -0.761541

In [186]:
frame = pd.DataFrame({ "Unemployment Prediction": dat[dat["INDICATOR"]=="Unemployment"]["Preds"], "Year": dat[dat["INDICATOR"]=="Unemployment"]["YEAR BEING FORECAST"]})
groupedune = frame.groupby("Year").mean()
groupedune

Unemployment Prediction
Year                         
2022                 7.129896
2023                 6.973807
2024                 7.014714

In [187]:
frame = pd.DataFrame({ "Core PCE Prediction": dat[dat["INDICATOR"]=="Core PCE"]["Preds"], "Year": dat[dat["INDICATOR"]=="Core PCE"]["YEAR BEING FORECAST"]})
groupedpce = frame.groupby("Year").mean()
groupedpce

Core PCE Prediction
Year                     
2022             1.452295

In [188]:
frame = pd.DataFrame({ "Core CPI Prediction": dat[dat["INDICATOR"]=="Core CPI"]["Preds"], "Year": dat[dat["INDICATOR"]=="Core CPI"]["YEAR BEING FORECAST"]})
groupedcpi = frame.groupby("Year").mean()
groupedcpi

Core CPI Prediction
Year                     
2022             1.782852

# Use Gridsearch Results

In [72]:
uX = dfs[["XGBoost Unemployment", "Random Forest Unemployment"]]
uY = dfs[["Unemployment actual"]]

uX = uX.dropna()
uY = uY.dropna()

In [73]:
gX = dfs[["XGBoost RealGDP", "Random Forest RealGDP"]]
gY = dfs[["RealGDP actual"]]

In [74]:
cX = dfs[["XGBoost Core CPI", "Random Forest Core CPI"]]
cY = dfs[["Core CPI actual"]]

cX = cX.dropna()
cY = cY.dropna()

In [75]:
pX = dfs[["XGBoost Core PCE", "Random Forest Core PCE"]]
pY = dfs[["Core PCE actual"]]

pX = pX.dropna()
pY = pY.dropna()

In [76]:
reg = LinearRegression().fit(gX, gY)
print(reg.score(gX, gY))

pred = reg.predict(gX)
actual = gY

np.sqrt(mean_squared_error(pred, actual))

0.9546869021295435


0.4100763638910511

In [77]:
reg.coef_

array([[0.42815693, 0.57616913]])

In [78]:
reg = LinearRegression().fit(uX, uY)
print(reg.score(uX, uY))

pred = reg.predict(uX)
actual = uY

np.sqrt(mean_squared_error(pred, actual))

0.9442919819963325


0.6702318731501157

In [79]:
reg.coef_

array([[0.74354694, 0.26637404]])

In [80]:
reg = LinearRegression().fit(cX, cY)
print(reg.score(cX, cY))

pred = reg.predict(cX)
actual = cY

np.sqrt(mean_squared_error(pred, actual))

0.922610484523368


0.337232509244397

In [81]:
reg.coef_

array([[-0.45484695,  1.50678078]])

In [82]:
reg = LinearRegression().fit(pX, pY)
print(reg.score(pX, pY))

pred = reg.predict(pX)
actual = pY

np.sqrt(mean_squared_error(pred, actual))

0.9039947016794517


0.37225918993422225

In [83]:
reg.coef_

array([[0.41344445, 0.59470852]])