In [45]:
import pandas as pd
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

In [46]:
df = pd.read_csv("results.csv")

In [47]:
dfs = pd.read_csv("results_post_gridsearch.csv")

In [48]:
dfs

Unemployment  ...  Random Forest Core PCE
0     Unemployment  ...                1.246261
1     Unemployment  ...                1.351786
2     Unemployment  ...                1.640270
3     Unemployment  ...                1.722364
4     Unemployment  ...                1.703876
...            ...  ...                     ...
2665           NaN  ...                     NaN
2666           NaN  ...                     NaN
2667           NaN  ...                     NaN
2668           NaN  ...                     NaN
2669           NaN  ...                     NaN

[2670 rows x 16 columns]

In [49]:
df

Unemployment  ...  KNeigborsRegressor Core PCE
0     Unemployment  ...                     1.237391
1     Unemployment  ...                     1.439257
2     Unemployment  ...                     1.647664
3     Unemployment  ...                     1.727602
4     Unemployment  ...                     1.975634
...            ...  ...                          ...
2665           NaN  ...                          NaN
2666           NaN  ...                          NaN
2667           NaN  ...                          NaN
2668           NaN  ...                          NaN
2669           NaN  ...                          NaN

[2670 rows x 24 columns]

In [50]:
uX = df[["XGBoost Unemployment", "Random Forest Unemployment", "Linear Regression Unemployment", "KNeigborsRegressor Unemployment"]]
uY = df[["Unemployment actual"]]

uX = uX.dropna()
uY = uY.dropna()

In [51]:
gX = df[["XGBoost RealGDP", "Random Forest RealGDP", "Linear Regression RealGDP", "KNeigborsRegressor RealGDP"]]
gY = df[["RealGDP actual"]]

In [52]:
cX = df[["XGBoost Core CPI", "Random Forest Core CPI", "Linear Regression Core CPI", "KNeigborsRegressor Core CPI"]]
cY = df[["Core CPI actual"]]

cX = cX.dropna()
cY = cY.dropna()

In [53]:
pX = df[["XGBoost Core PCE", "Random Forest Core PCE", "Linear Regression Core PCE", "KNeigborsRegressor Core PCE"]]
pY = df[["Core PCE actual"]]

pX = pX.dropna()
pY = pY.dropna()

In [54]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [55]:
def create_mlp(dim, regress=False):
	# define our MLP network
	model = Sequential()
	model.add(Dense(8, input_dim=dim, activation="relu"))
	model.add(Dense(4, activation="relu"))
	# check to see if the regression node should be added
	if regress:
		model.add(Dense(1, activation="linear"))
	# return our model
	return model

In [56]:
#from tensorflow.keras.optimizers import Adam
#from sklearn.model_selection import train_test_split
#import numpy as np
#import argparse
#import locale
#import os

#model = create_mlp(uX.shape[1], regress=True)
#opt = Adam(lr=1e-3, decay=1e-3 / 200)
#model.compile(loss="mean_absolute_percentage_error", optimizer=opt)
## train the model
#print("[INFO] training model...")
#model.fit(x=uX, y=uY, #
#	validation_data=(uX, uY),#
#	epochs=200, batch_size=8)

In [57]:
#preds = model.predict(uX)

In [58]:
#preds

In [59]:
from sklearn.linear_model import LinearRegression

In [60]:
reg = LinearRegression().fit(gX, gY)
reg.score(gX, gY)

0.9549310708629474

In [61]:
reg.predict(gX)

array([[2.56188736],
       [4.1774761 ],
       [4.15642966],
       ...,
       [4.21928957],
       [2.43410261],
       [4.23721564]])

In [62]:
reg.coef_

array([[ 0.39451943,  0.62355299, -0.00584316, -0.0121875 ]])

In [63]:
from sklearn.metrics import mean_squared_error

pred = reg.predict(gX)
actual = gY

np.sqrt(mean_squared_error(pred, actual))

0.4089700273137137

In [64]:
reg = LinearRegression().fit(gX, gY)
print(reg.score(gX, gY))

pred = reg.predict(gX)
actual = gY

np.sqrt(mean_squared_error(pred, actual))

0.9549310708629474


0.4089700273137137

In [65]:
reg.coef_

array([[ 0.39451943,  0.62355299, -0.00584316, -0.0121875 ]])

In [66]:
reg = LinearRegression().fit(uX, uY)
print(reg.score(uX, uY))

pred = reg.predict(uX)
actual = uY

np.sqrt(mean_squared_error(pred, actual))

0.9437394066880166


0.6735477307884534

In [67]:
reg.coef_

array([[0.56704491, 0.40050452, 0.01584245, 0.03268518]])

In [68]:
reg = LinearRegression().fit(cX, cY)
print(reg.score(cX, cY))

pred = reg.predict(cX)
actual = cY

np.sqrt(mean_squared_error(pred, actual))

0.9251698478091955


0.33160928669688405

In [69]:
reg.coef_

array([[-0.09791807,  1.20435237,  0.06206949, -0.06951675]])

In [70]:
reg = LinearRegression().fit(pX, pY)
print(reg.score(pX, pY))

pred = reg.predict(pX)
actual = pY

np.sqrt(mean_squared_error(pred, actual))

0.9311808648943892


0.31517548684660446

In [71]:
reg.coef_

array([[ 1.23070382, -0.22976726, -0.00268178, -0.04048661]])

Use Gridsearch Results

In [72]:
uX = dfs[["XGBoost Unemployment", "Random Forest Unemployment"]]
uY = dfs[["Unemployment actual"]]

uX = uX.dropna()
uY = uY.dropna()

In [73]:
gX = dfs[["XGBoost RealGDP", "Random Forest RealGDP"]]
gY = dfs[["RealGDP actual"]]

In [74]:
cX = dfs[["XGBoost Core CPI", "Random Forest Core CPI"]]
cY = dfs[["Core CPI actual"]]

cX = cX.dropna()
cY = cY.dropna()

In [75]:
pX = dfs[["XGBoost Core PCE", "Random Forest Core PCE"]]
pY = dfs[["Core PCE actual"]]

pX = pX.dropna()
pY = pY.dropna()

In [76]:
reg = LinearRegression().fit(gX, gY)
print(reg.score(gX, gY))

pred = reg.predict(gX)
actual = gY

np.sqrt(mean_squared_error(pred, actual))

0.9546869021295435


0.4100763638910511

In [77]:
reg.coef_

array([[0.42815693, 0.57616913]])

In [78]:
reg = LinearRegression().fit(uX, uY)
print(reg.score(uX, uY))

pred = reg.predict(uX)
actual = uY

np.sqrt(mean_squared_error(pred, actual))

0.9442919819963325


0.6702318731501157

In [79]:
reg.coef_

array([[0.74354694, 0.26637404]])

In [80]:
reg = LinearRegression().fit(cX, cY)
print(reg.score(cX, cY))

pred = reg.predict(cX)
actual = cY

np.sqrt(mean_squared_error(pred, actual))

0.922610484523368


0.337232509244397

In [81]:
reg.coef_

array([[-0.45484695,  1.50678078]])

In [82]:
reg = LinearRegression().fit(pX, pY)
print(reg.score(pX, pY))

pred = reg.predict(pX)
actual = pY

np.sqrt(mean_squared_error(pred, actual))

0.9039947016794517


0.37225918993422225

In [83]:
reg.coef_

array([[0.41344445, 0.59470852]])